spring.application.name=everest-site
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
api.security.token.secret=${ALGORITHM_SECRET}