spring.application.name=everest-site
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.security.user.name=${ADMIN_EMAIL}
spring.security.user.password=${ADMIN_PASSWORD}
api.security.token.secret=${ALGORITHM_SECRET}