server.port=8081
spring.application.name=${AUTH_ID}

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=host.docker.internal
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.security.user.name=${ADMIN_EMAIL}
spring.security.user.password=${ADMIN_PASSWORD}
api.security.token.secret=${ALGORITHM_SECRET}